### ISSUE TITLE
About "You must include the same interface classes with server side in your client side project"

### ISSUE THREAD

**Issue by goribun** [nofdev/service-client-java#1]
May be resolved through develop  the Maven or Gradle plug-in

**Comment by mengqiang81** [comment]
LGTM. 
It is a plan, i want to extract and publish the interface classes package jar from the server side automatically.

**Comment by houdq** [comment]
So... what's meaning of 'LGTM.'?

**Comment by goribun** [comment]
LOOKS GOOD TO ME @psycoHo

**Comment by goribun** [comment]
LOOKS GOOD TO ME 😁

王雪松  17090889288
xswang@outlook.commailto:xswang@outlook.com
✉

在 2016年3月25日，下午5:09，psyco <notifications@github.com<mailto:notifications@github.com>> 写道：

So... what's meaning of 'LGTM.'?

**Comment by pootow** [comment]
This is not a big problem, you can include dependencies yourself. Further plan see nofdev-prc-jsonidl project.
