### ISSUE TITLE
SDK makes PRC call of toString() method while debugging

### ISSUE THREAD

**Issue by tian0cai** [nofdev/service-client-java#2]
如下代码：
HttpJsonProxy proxy = new HttpJsonProxy(InputFacade.class, baseUrl);
InputFacade facade = (InputFacade) proxy.getObject();
facade.bulkInput(productDTOList);
当在这段代码的最后一行打断点时会多调用两次toString()方法。

**Comment by goribun** [comment]
感觉是断点导致了请求超时造成的

**Comment by mengqiang81** [comment]
是 IDE 断点要调用 toString() 方法获取基本信息. 而客户端目前的逻辑是会把所有接口方法转为远程调用, 1.10版会 fix 这个问题.

**Comment by pootow** [comment]
fixed in 1.10
